apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: discord-comics
  name: heathcliff-wattba
  namespace: discord-comics
spec:
  schedule: CRON_TZ=America/New_York 0 8 * * *
  successfulJobsHistoryLimit: 1 # Keep only 1 successful run
  failedJobsHistoryLimit: 3     # Keep up to 3 failed runs (optional)
  jobTemplate:
    metadata:
      labels:
        app: discord-comics
      name: heathcliff-wattba
    spec:
      template:
        metadata:
          labels:
            app: discord-comics
          name: heathcliff-wattba
        spec:
          restartPolicy: OnFailure
          containers:
          - env:
            - name: DISCORD_WEBHOOK_URL
              value: https://discord.com/api/webhooks/1183245327638208542/kFaZ9UwIspuI2RDYl6doZE0jzNv44MYiJc_TopGM3HmjVEH00k63j_CKn6DOy3TReB73
            - name: RSS_URL
              value: http://www.comicsrss.com/rss/heathcliff.rss
            image: tupperward/discord-comics:latest
            imagePullPolicy: Always
            name: heathcliff-wattba
            resources:
              limits:
                cpu: 50m
                memory: 128Mi
              requests:
                cpu: 10m
            